name: Draw.io Images Update

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: severgroup-tt/actions-drawio-cli@v0.0.2
        with:
          source: doc
          destination: doc
          format: png
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: doc/*.png
          commit_message: Update diagrams
